### ISSUE TITLE
Bug Casa

### ISSUE THREAD

**Issue by Ghas95** [keldix/AetherIssues#1]
**Describe the bug**
Una casa ha gli interior sbagliati.

**To Reproduce**
Entra in casa 13 Melanoma Street (South Beach)

**Expected behavior**
Dovrebbe avere gli interior e il prezzo delle case 5 Melanoma Street e 7 Melanoma Street + la possibilità di affitto.

**Screenshots**
![Immagine](https://user-images.githubusercontent.com/79383092/119161205-553f4e80-ba59-11eb-9038-b32e86608f88.png)

**Desktop (please complete the following information):**
 - Server: Aether
 - Date and Time: 21/05/2021 17:24

**Additional context**

**Comment by keldix** [comment]
fixed (loaf_housing is shit)
