### ISSUE TITLE
[BUG] Non è possibile modificare la visuale durante i tatuaggi

### ISSUE THREAD

**Issue by Bonnolo** [keldix/AetherIssues#13]
**Describe the bug**
Vedo l'interno del pg quando scelgo un tatuaggio

**To Reproduce**
1. Finire la Prima creazione del pg
2. Si apre la sezione tatuaggi e scegliere un tatuaggio
3. Premendo Maiusc SX non ti fa ruotare la cam ed è fissa all'interno del personaggio

**Expected behavior**
Posso spostare la visuale durante la scelta del tatuaggio premendo Maiusc SX

**Server (please complete the following information):**
 - Server: Aether
 - Date and Time: 21/05/2021 | 21:30 (ca.)

**Comment by saamdotexe** [comment]
Non replicabile
