### ISSUE TITLE
[BUG] Se scassini il veicolo al concessionario durante la visione dello stesso

### ISSUE THREAD

**Issue by Bonnolo** [keldix/AetherIssues#15]
**Describe the bug**
Se visioni un veicolo qualsiasi e tendi di scassinarlo rimani bloccato e non puoi più agire in alcun modo.

**To Reproduce**
1. Vai al marker del concessionario per vedere i veicoli
2. Seleziona un veicolo qualsiasi
3. Scassinalo

**Expected behavior**
Non poter scassinare il veicolo.

**Server (please complete the following information):**
 - Server:  Aether
 - Date and Time: 21/05/2021 22:00 (ca.)

**Comment by keldix** [comment]
fixed, now it gives keys
