### ISSUE TITLE
[BUG] Se il veicolo e distrutto non ti fa scendere in alcun modo

### ISSUE THREAD

**Issue by Bonnolo** [keldix/AetherIssues#17]
**Describe the bug**
Se il veicolo e distrutto, ovvero non più utilizzabile non puoi più scendere

**To Reproduce**
1. Distruggi il veicolo
2. See error

**Expected behavior**
Che puoi scendere

**Server (please complete the following information):**
 - Server: Aether
 - Date and Time: 21/05/2021 23:00 ca.

**Comment by keldix** [comment]
Unable to reproduce, may have had seatbelt

**Comment by Bonnolo** [comment]
To Reproduce
Steps to reproduce the behavior:

1. Distruggi il veicolo
2. Vai al autolavaggio
3. Premi 'E' per lavare il veicolo
4. Finito il lavaggio non puoi scendere

**Comment by keldix** [comment]
will never happen anyway
