### ISSUE TITLE
Lampeggianti veicoli (extra EMS/LSPD)

### ISSUE THREAD

**Issue by Ghas95** [keldix/AetherIssues#22]
**Describe the bug**t
emscharg e lspddom spawnano senza lampeggianti

**To Reproduce**
/car emscharg oppure /car lspddom

**Expected behavior**
Tutti gli extra dovrebbero sempre essere equipaggiati

**Screenshots**
![image](https://user-images.githubusercontent.com/79383092/119207799-c86bb380-ba9f-11eb-805d-df41e5b3a43d.png)

**Server (please complete the following information):**
 - Server: tutti
 - Date and Time: 22/05/2021 01:42

**Additional context**
//

**Comment by keldix** [comment]
done
