### ISSUE TITLE
[BUG] Rimani bloccato nelle case in affitto

### ISSUE THREAD

**Issue by Bonnolo** [keldix/AetherIssues#28]
**Describe the bug**
Dopo aver affittato casa e provi a entrare al garage ti dice giustamente che sei in affitto. Se ti allontani dalla porta e poi ti riavvicini non puoi più uscire 

**To Reproduce**
1. Affitta casa
2. Entraci
3. Una volta dentro seleziona 'garage'
4. Allontanati dalla porta fino a quando non vedi più 'Premi E'
5. Non ti apre più ll'interfaccia quindi di conseguenza rimani bloccato in casa

**Expected behavior**
Ti apre l'interfaccia e puoi uscire.

**Screenshots**
   N/A

**Server (please complete the following information):**
 - Server:  Aether
 - Date and Time: 22/05/2021 21:40

**Additional context**
E' successo due volte di seguito

**Comment by keldix** [comment]
fine
