### ISSUE TITLE
[BUG] Megastore not working

### ISSUE THREAD

**Issue by Bonnolo** [keldix/AetherIssues#29]
**Describe the bug**
Non si apre il l'inventario del Megastore ma ti apre il tuo e rimane il suggerimento del tasto 'Premi F3'

**To Reproduce**
1. Vai al megastore
2. Quando ti appare la scritta in basso 'Premi F3'
3. Premendo 'F3' ti apre il tuo di inventario
4. Rimane la scritta 'F3' in basso dello schermo

**Expected behavior**
Puoi aprire il negozio e non deve rimanere la scritta in basso anche quando ti allontani

**Screenshots**
![image](https://user-images.githubusercontent.com/84602400/119239283-61560980-bb48-11eb-9989-54c31c9304ea.png)
![image](https://user-images.githubusercontent.com/84602400/119239288-6915ae00-bb48-11eb-848d-49cf0e6a8d45.png)
![image](https://user-images.githubusercontent.com/84602400/119239300-7a5eba80-bb48-11eb-89b6-6865a6cb7c3a.png)

**Server (please complete the following information):**
 - Server: Aether
 - Date and Time:  22/05/2021 | 21:56

**Comment by keldix** [comment]
fixed
