### ISSUE TITLE
[BUG] Job NON FUNZIONANTI 

### ISSUE THREAD

**Issue by ReMidas1** [keldix/AetherIssues#30]
**Describe the bug**
* Job Petroliere ha la scritta rotta e non parte il job. 
* Nel job netturbino fatto il primo giro rimane fisso il blip sul cassonetto e non ti fa iniziare un altro job. 
* sono da settare tutti i pagamenti dei job

**To Reproduce**
1. Go to 'Azienda petrolio'
2. Click on 'blip per iniziare lavoro'
3. See error

**Expected behavior**
spostare blip sulla porta del prefabbricato e fixxare scritte e start job e se possibile mettere i blip dei camion al posto di quelli delle auto
**Screenshots**
![20210522214927_1](https://user-images.githubusercontent.com/84603085/119239359-cf023580-bb48-11eb-9bb0-7572705715ea.jpg)

![20210522215420_1](https://user-images.githubusercontent.com/84603085/119239362-d295bc80-bb48-11eb-8644-91161b497bab.jpg)

![20210522215910_1](https://user-images.githubusercontent.com/84603085/119239398-1b4d7580-bb49-11eb-9d55-663d64b26870.jpg)

![20210522215930_1](https://user-images.githubusercontent.com/84603085/119239401-1e486600-bb49-11eb-9664-bf6324ef9ef0.jpg)

**Comment by keldix** [comment]
![1555064462_Pepega](https://user-images.githubusercontent.com/79382417/119245882-ef4be780-bb7c-11eb-8782-5de87fff727a.gif)

**Comment by saamdotexe** [comment]
Fixato quello che potevo senza incazzarmi e buttare lo script

**Comment by ShadowITA** [comment]
![image](https://user-images.githubusercontent.com/79382468/119253142-196acd00-bbb0-11eb-86e7-76ebf3f7515e.png)

**Comment by ShadowITA** [comment]
stessa cosa netturbino.

**Comment by ShadowITA** [comment]
Fixed.
