### ISSUE TITLE
[BUG] Vestiti 'Top' da uomo a donna e viceversa

### ISSUE THREAD

**Issue by Bonnolo** [keldix/AetherIssues#31]
**Describe the bug**
Non ti mette il vestito.

**To Reproduce**
1. Settati la skin donna
2. Prendi il vestito da uomo e indossalo
3. See error

**Expected behavior**
Te lo indossa.

**Screenshots**
![image](https://user-images.githubusercontent.com/84602400/119239429-37e9ad80-bb49-11eb-8984-8eb03790e59a.png)
![image](https://user-images.githubusercontent.com/84602400/119239435-4932ba00-bb49-11eb-87d3-713cfdde5d39.png)
![image](https://user-images.githubusercontent.com/84602400/119239441-518af500-bb49-11eb-96f4-1f1dba647c69.png)

**Server (please complete the following information):**
 - Server:  Aether
 - Date and Time:  22/05/2021 22:00

**Comment by keldix** [comment]
fixed even tho some clothing are pepega
