### ISSUE TITLE
[BUG] Autoammanettamento con /cuffs

### ISSUE THREAD

**Issue by ReMidas1** [keldix/AetherIssues#34]
**Describe the bug**
Lion si è bloccato senza possibilità di far nulla

**To Reproduce**
In auto mentre guidava ha fatto /cuffs e il gioco ha contato come se fosse ammanettato ( aveva le manette ai polsi come se si fosse autoammanettato ), per fixxare ho dovuto fare /dv al veicolo, ammanettarlo e smanettarlo

**Expected behavior**
sarebbe da rimuovere questa animazione

**Comment by saamdotexe** [comment]
Fixed
