### ISSUE TITLE
[BUG] Ogni tanto i menu base si aprono e si chiudono subito

### ISSUE THREAD

**Issue by saamdotexe** [keldix/AetherIssues#36]
**Describe the bug**
Ogni tanto i menu base si aprono e si chiudono subito

**To Reproduce**
Passaggi sconosciuti

**Comment by keldix** [comment]
unable to replicate

**Comment by saamdotexe** [comment]
SimplyAlen è spawnato, ha fatto i vestiti, ha scassinato una macchina, ha aperto social intruder e si sono buggati i menu

**Comment by saamdotexe** [comment]
Replicato noleggiando un faggio
