### ISSUE TITLE
[BUG] Telefono App Banka [Solo a TheBarsa]

### ISSUE THREAD

**Issue by Bonnolo** [keldix/AetherIssues#55]
**Describe the bug**
Il telefono di barsa si blocca all'apertura dell app banca

**To Reproduce**
N/A

**Expected behavior**
Che funzioni

**Server (please complete the following information):**
 - Server: Aether
 - Date and Time: 23/05/2021 

**Additional context**
Durante la creazione del pg è dovuto sloggare e riloggare e non credo che gli abbia fatto la tabella nel db della banka or smth like that
Anche se slogga e rilogga non si fixxa

**Comment by Bonnolo** [comment]
Non riesco a riprodurlo ma se slogghi durante la creazione del pg sezione tatuaggi una volta che apri l'app della banca ti dice nel numero conto undefinded!!

**Comment by keldix** [comment]
unable to reproduce
