### ISSUE TITLE
[BUG] Sim

### ISSUE THREAD

**Issue by Bonnolo** [keldix/AetherIssues#56]
**Describe the bug**
Al primo log in con creazione del pg se utilizzi la sim te la rinomina poi si rompe tutto con il mouse utilizzabile 
Non puoi più interagire con nulla sei immobile come una statuetta e ti tocca sloggare e rientrare e poi la devi ri-rinominare.

**To Reproduce**
N/A

**Expected behavior**
Che ti rinomini la sim e dopo possa muoverti

**Server (please complete the following information):**
 - Server: Aether
 - Date and Time: 23/05/2021

**Comment by keldix** [comment]
fixed on menudefault fix
