### ISSUE TITLE
[BUG] AE-menu_list:message:menu_cancel crasha i player (Chaos)

### ISSUE THREAD

**Issue by saamdotexe** [keldix/AetherIssues#6]
**Describe the bug**
L'event AE-menu_list:message:menu_cancel fa crashare con Chaos

**To Reproduce**
Sconosciuto

**Expected behavior**
Non dovresti crashare

**Screenshots**
https://imgur.com/XxbpLgq.png

**Server (please complete the following information):**
 - Aether

**Comment by keldix** [comment]
fixed
