### ISSUE TITLE
[BUG] Medikit senza immagine

### ISSUE THREAD

**Issue by Ghas95** [keldix/AetherIssues#60]
**Describe the bug**
Il medikit appare senza immagine nell'inventario.

**To Reproduce**
/giveitem me medikit 1 ,F3

**Expected behavior**
L'item dovrebbe avere l'immagine.

**Screenshots**
![Medikit](https://user-images.githubusercontent.com/79383092/119271154-9d4ca580-bc00-11eb-8bea-bbe694752d92.png)

**Server (please complete the following information):**
 - Server: tutti
 - Date and Time: 23/05/2021 19:54

**Additional context**
//

**Comment by keldix** [comment]
added by @Mans-07
