### ISSUE TITLE
[BUG] Creator 

### ISSUE THREAD

**Issue by Bonnolo** [keldix/AetherIssues#67]
**Describe the bug**
Si blocca la cam (zoomout) dopo aver selezionato 'torso'.

**To Reproduce**
1. Create new pg
2. Spammate le cam
3. See error

**Expected behavior**
Cams should keep changing.

**Server (please complete the following information):**
 - Server: Hemera
 - Date and Time: 25/05/2021 16:00 ca

**Comment by keldix** [comment]
will never know, not able to reproduce consistently

**Comment by keldix** [comment]
duplicate
