### ISSUE TITLE
[BUG] Telefono [cancella chat]

### ISSUE THREAD

**Issue by Bonnolo** [keldix/AetherIssues#79]
**Describe the bug**
If both players deleted their message and then want to open a new text chat on WApp the number displayed on top is "Undefined"

**To Reproduce**
1. Create a new chat
2. Send some messages from both ends
3. Delete the messages send from both ends
4. Check if the chat is completely deleted
5. Try to send a new message to the same number
6. See error

**Expected behavior**
You should be able to send new messages to the same number

**Screenshots**
![image](https://user-images.githubusercontent.com/84602400/120078784-6a4b5b80-c0b1-11eb-8008-b92ba8574a7d.png)

**Server (please complete the following information):**
 - Server: Aether
 - Date and Time: 05/29/2021 19:09

**Additional context**
Tested with Rex

**Comment by keldix** [comment]
fixed
