### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Ghas95** [keldix/AetherIssues#88]
**Describe the bug**
Il minigioco forme-colori, a fine tempo si blocca definitivamente

**To Reproduce**
Vai nel casinò ad hackerare una porta
Attendi fino alla fine del tempo del minigioco
Sei obbligato a fare F8 quit

**Expected behavior**
Il minigioco dovrebbe dare errore quando finisce il tempo

**Screenshots**
![image](https://user-images.githubusercontent.com/79383092/121683871-41b65f00-cabe-11eb-8863-976514147195.png)

**Server (please complete the following information):**
 - Server: Aether
 - Date and Time: 11/06/2021 14:10

**Comment by keldix** [comment]
risolto some time ago
