### ISSUE TITLE
[BUG] Extra veicoli ripara

### ISSUE THREAD

**Issue by Ghas95** [keldix/AetherIssues#89]
**Describe the bug**
Quando un veicolo ha una gomma bucata, metti e togli un extra e si ripara e recupera carburante fino al 70%

**To Reproduce**
1. Sali su un veicolo non danneggiato, ma con la ruota bucata
2. Clicca F1 - Extra - Disattivato/Attivato
3. Disattiva e Riattiva un Extra
4. La ruota si riparerà e il veicolo recupererà carburante

**Expected behavior**
L'extra dovrebbe apparire/disapparire senza modificare i danni/livelli di carburante

**Server (please complete the following information):**
 - Server: Aether
 - Date and Time: 30/06/2021 14:44

**Comment by keldix** [comment]
thats how mafia works
